name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build and Push Docker to Docker Hub"]
    types:
      - completed
    branches:
      - develop
      - master
      - release

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Docker Image Tag
        id: tag
        run: |
          REF=${{ github.event.workflow_run.head_ref }}
          if [[ "$REF" == "refs/heads/develop" ]]; then
            SHORT_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)
            echo "tag=develop-${SHORT_SHA}" >> $GITHUB_ENV
          elif [[ "$REF" == "refs/tags/v"* ]]; then
            TAG=${REF#refs/tags/}
            echo "tag=$TAG" >> $GITHUB_ENV
          else
            echo "Неизвестная ветка или тег: $REF. Выход..."
            exit 1
          fi

      - name: Debug info
        run: |
          echo "Ref: ${{ github.event.workflow_run.head_ref }}"
          echo "SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Tag: ${{ env.tag }}"

      - name: Pull and restart Docker container
        env:
          IMAGE_NAME: shifter1703/fungicibus
        run: |
          BRANCH=$(echo "${{ github.event.workflow_run.head_branch }}")
          if [[ "$BRANCH" == "develop" ]]; then
            PORT=8081
          elif [[ "$BRANCH" == "release" ]]; then
            PORT=8082
          elif [[ "$BRANCH" == "master" ]]; then
            PORT=8083
          else
            echo "Неизвестная ветка: $BRANCH. Выход..."
            exit 1
          fi
          docker pull $IMAGE_NAME:${{ env.tag }}
          docker stop app_$BRANCH || true
          docker rm app_$BRANCH || true
          docker run -d --name app_$BRANCH -p $PORT:80 $IMAGE_NAME:${{ env.tag }}